name: Build

on:
  push:
    branches: 
        - '*'
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build
      run: dotnet build ./src/FortniteReplayDecompressor.sln --configuration Release
    - name: Test
      run: dotnet test ./src/FortniteReplayDecompressor.sln /p:CollectCoverage=true /p:CoverletOutputFormat="lcov" /p:CoverletOutput="../../coverage/lcov.info" /p:Exclude=\"[Fortnite*]*.Models.*\" --no-build --configuration Release
    - name: Coveralls
      if: ${{ matrix.os }} == ubuntu-latest
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}