name: Build

on:
  push:
    branches: master
    tags: '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build
      run: dotnet build ./src/FortniteReplayDecompressor.sln --configuration Release
    - name: Test
      run: dotnet test ./src/FortniteReplayDecompressor.sln /p:CollectCoverage=true /p:CoverletOutputFormat="opencover" /p:CoverletOutput="../../coverage/coverage.xml" --no-build --configuration Release --filter FullyQualifiedName!=Unreal.Encryption.Test.OodleDecompressTest.DecompressTest
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: "./coverage/coverage.xml"